config/routes.rb
Rails.application.routes.draw do
  resources :images
  root 'welcome#index'
  devise_for :users, :controllers => { :registrations => 'registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  has_one_attached :picture
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  attr_accessor :card_number, :card_cvv, :card_expires_month, :card_expires_year

  belongs_to :user

  def self.month_options
    Date::MONTHNAMES.compact.each_with_index.map { |name, i| ["#{i+1} - #{name}", i+1] }
  end

  def self.year_options
    (Date.today.year..(Date.today.year+10)).to_a
  end

  def process_payment
    customer = Stripe::Customer.create(email: user.email, card: token)
    Stripe::Charge.create(
      customer: customer.id,
      amount: 1000,
      description: 'Premium',
      currency: 'usd'
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
 # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable , :validatable
  has_one :payment
  accepts_nested_attributes_for :payment
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[show edit update destroy]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)
    @image.user = current_user
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = Image.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def image_params
    params.require(:image).permit(:name, :picture)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(sign_up_params)
    resource.class.transaction do
      resource.save
      yield resource if block_given?
      if resource.persisted?
        @payment = Payment.new(email: params["user"]["email"], token: params[:payment]["token"], user_id: resource.id)
        flash[:error] = "Please check registration errors" unless @payment.valid?
        begin
          @payment.process_payment
          @payment.save
        rescue Exception => e
          flash[:error] = e.message
          resource.destroy
          puts 'Payment failed'
          render :new and return
        end
        if resource.active_for_authentication?
          set_flash_message :notice, :signed_up if is_flashing_format?
          sign_up(resource_name, resource)
          respond_with resource, location: after_sign_up_path_for(resource)
        else
          set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
          expire_data_after_sign_in!
          respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end
      else
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:payment])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image) do |form| %>
  <% if image.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :picture, style: "display: block" %>
    <%= form.file_field :picture %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/images/_image.html.erb
<div id="<%= dom_id image %>">
  <p>
    <strong>Name:</strong>
    <%= image.name %>
  </p>

  <p>
    <strong>Picture:</strong>
    <%= image.picture %>
  </p>

  <p>
    <strong>User:</strong>
    <%= image.user_id %>
  </p>

</div>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Show this image", @image %> |
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Images</h1>

<div id="images">
  <% @images.each do |image| %>
    <%= render image %>
    <p>
      <%= link_to "Show this image", image %>
    </p>
  <% end %>
</div>

<%= link_to "New image", new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @image %>
<h1>Image Details</h1>

<p><strong>Name:</strong> <%= @image.name %></p>

<h1>Image Details</h1>

<p><strong>Name:</strong> <%= @image.name %></p>

<div>
  <% if @image.picture.attached? %>
    <%= image_tag url_for(@image.picture) %>
  <% end %>
</div>

<div>
  <%= link_to "Edit this image", edit_image_path(@image) %> |
  <%= link_to "Back to images", images_path %>

  <%= button_to "Destroy this image", @image, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
    <%= javascript_importmap_tags %>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar scroll</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Link
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <%= link_to 'Signout', destroy_user_session_path ,method: :delete ,data: { turbo_method: :delete } , class: 'nav-item' %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<% if current_user %>
  <div class="jumbotron">
    <h2>Welcome to the Photo Management App!</h2>
    <p class="lead">
      You'll love managing your Photos with our application. Sign up!
    </p>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-header">
          <h2>Premium Plan</h2>
        </div>
        <div class="card-body">
          <div class="price pull-right">
            Price: $10
          </div>
          <div class="features">
            <ul>
              <li>Unlimited Image Uploads</li>
              <li>Responsive design</li>
              <li>Access anywhere</li>
            </ul>
          </div>
          <p>
            <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary sign-up' %>
          </p>
        </div>
      </div>
    </div>

    <div class="col-lg-6">
      <div class="card">
        <div class="card-header">
          <h2>Amaze Plan</h2>
        </div>
        <div class="card-body">
          <div class="price pull-right">
            Price: $20
          </div>
          <div class="features">
            <ul>
              <li>Unlimited Image Uploads</li>
              <li>Responsive design</li>
              <li>Access anywhere</li>
              <li class="extra">Unlimited projects</li>
            </ul>
          </div>
          <p>
            <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary sign-up' %>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>